# Generated by Django 6.0.3 on 2026-03-25 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geofences', '0001_initial'),
        ('hazards', '0003_delete_alertlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('hazard', 'Hazard'), ('geofence', 'Geofence')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='geofences.geofence')),
                ('hazard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_alerts', to='hazards.hazardevent')),
            ],
        ),
    ]
