# Generated by Django 6.0.3 on 2026-03-25 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('approaching_hazard', 'Approaching Hazard')], default='approaching_hazard', max_length=50)),
                ('checked_latitude', models.FloatField()),
                ('checked_longitude', models.FloatField()),
                ('distance_meters', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='hazards.hazardevent')),
            ],
        ),
    ]
