# Generated by Django 6.0.3 on 2026-03-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0002_alertlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertLog',
        ),
    ]
