# Generated by Django 6.0.3 on 2026-03-25 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofences', '0001_initial'),
        ('hazards', '0004_videoupload_hazardreport_video_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geofence',
            name='source_hazard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_geofence', to='hazards.hazardevent'),
        ),
    ]
